apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: frontend-ingress
  namespace: kraft
spec:
  rules:
  - host: frontendmu.alexbissessur.dev
    http:
      paths:
      - backend:
          service:
            name: frontendmu
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
